# Generated by Django 5.2 on 2025-05-28 07:52

import core.models.user_details
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload your CV (PDF, DOC, DOCX)', null=True, upload_to=core.models.user_details.get_upload_path),
        ),
    ]
