# Generated by Django 5.2 on 2025-05-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interest'),
        ),
    ]
