# Generated by Django 5.1.7 on 2025-05-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cv_text',
            field=models.TextField(blank=True, help_text='Extracted text from CV file', null=True),
        ),
    ]
