# Generated by Django 5.2 on 2025-04-16 10:40

import core.models.user_details
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='background_image_url',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_details.get_upload_path),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_details.get_upload_path),
        ),
    ]
