# Generated by Django 5.2 on 2025-04-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userdetails_background_image_url_and_more'),
    ]

    operations = [
    ]
